CB-1: Cooking time
knowde-academy/cookbook-be pull request #11
Opened 2021-07-23 12:05 UTC by Narzew

2021-07-26 12:42 UTC, akademia-knowde requested changes
missing specs for serializer

2021-07-26 12:42 UTC, akademia-knowde commented on app/serializers/recipe_serializer.rb
> +    end
```suggestion
      return  "unknown" unless object.cooking_time
  
      object.cooking_time
```

2021-07-26 12:42 UTC, akademia-knowde commented on config/database.yml
> +  username: niki
unnecessary

2021-07-26 12:42 UTC, akademia-knowde commented on .gitignore
> +/config/database.yml
missing new line char

2021-07-27 12:56 UTC, akademia-knowde requested changes

2021-07-27 12:56 UTC, akademia-knowde commented on app/serializers/recipe_serializer.rb
> +
unnecessary

2021-07-27 12:56 UTC, akademia-knowde commented on app/serializers/recipe_serializer.rb
> +    return "unknown" unless object.cooking_time
guard clause - pusta linia

2021-07-27 12:56 UTC, akademia-knowde commented on spec/serializers/recipe_serializer_spec.rb
> +end
newline

2021-07-27 12:56 UTC, akademia-knowde commented on spec/serializers/recipe_serializer_spec.rb
> +
unnecessary

2021-07-27 12:56 UTC, akademia-knowde commented on spec/serializers/recipe_serializer_spec.rb
> +    end
empty line

2021-07-29 08:52 UTC, h4b00 reviewed
please Add back `config/database.yml ` it should be in gitignore but it shouldn't be deleted from the repo.
rest work looks good 💯 !

2021-07-29 11:46 UTC, Narzew commented
> please Add back `config/database.yml ` it should be in gitignore but it shouldn't be deleted from the repo.
> rest work looks good  !

Done, I'm waiting for merge

2021-07-29 12:15 UTC, akademia-knowde approved these changes

2021-07-29 12:16 UTC, merged