Cb 6 add price field
knowde-academy/cookbook-be pull request #12
Opened 2021-07-27 12:05 UTC by grabomarcin

2021-07-29 09:19 UTC, h4b00 approved these changes
Nice good joob.
Please apply rubocop changes & my comment from there 👇  regarding model template.
https://github.com/knowde-academy/cookbook-be/pull/13/files#r678967472

2021-07-29 09:19 UTC, h4b00 commented on db/migrate/20210723120136_add_price_to_recipe.rb
> +
unnecessary empty line

2021-07-29 09:19 UTC, h4b00 commented on app/serializers/recipe_show_serializer.rb
> +
unnecessary empty line

2021-07-29 09:19 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +
unnecessary empty line

2021-07-29 09:19 UTC, h4b00 commented on db/seeds.rb
> +    tempor semper libero ultrices posuere. Maecenas id erat ac enim pharetra consequat.", price: 0.0)
💯  nice, good catch.
But use maybe something different than 0  ;)

2021-07-30 11:31 UTC, h4b00 requested changes

2021-07-30 11:31 UTC, h4b00 commented on .rubocop.yml
> +  Enabled: false
I would just increase limit instead of disabling that at all.

2021-07-30 11:31 UTC, h4b00 commented on db/migrate/20210723120136_add_price_to_recipe.rb
> +    add_column :recipes, :price, :decimal
You need to have precision here.
`, precision: 8, scale: 2`

2021-07-30 11:31 UTC, h4b00 commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +    let(:new_price) { 9 }
instead of checking params like that we can do something like this:

```
context 'with invalid price'
context 'with invalid name'
context 'with invalid video_link'

and inside of each of that context you can add there `let(:invalid_params) { price: -1 | name: '' | etc..}`

2021-07-30 11:31 UTC, h4b00 commented on spec/serializers/recipe_serializer_spec.rb
> +      let(:recipe) { create(:recipe, price: nil) }
use `.build` instead of `.create`

2021-07-30 11:31 UTC, h4b00 commented on app/controllers/api/v1/recipes_controller.rb
> +        render json: RecipeSerializer.new(@recipe).to_h
do you need this`.to_h`

2021-07-30 11:50 UTC, grabomarcin commented on app/controllers/api/v1/recipes_controller.rb
> +        render json: RecipeSerializer.new(@recipe).to_h
When I delete `.to_h` and run rspec, it returns this error:
`
  1) Api::V1::RecipesController [GET] #show returns requested recipe
     Failure/Error: render json: RecipeSerializer.new(@recipe)
     
     NoMethodError:
       undefined method `model_name' for RecipeSerializer:Class
       Did you mean?  module_parent`

2021-07-30 12:50 UTC, grabomarcin commented on .rubocop.yml
> +  Enabled: false
Michał disabled that option and merged his version with develop. Should I change it in my version? I think it would create some problems with tests in develop branch with another tests.

2021-07-31 08:05 UTC, h4b00 approved these changes

2021-07-31 08:05 UTC, h4b00 commented
Fix conflicts and feel free to merge.

2021-08-02 08:43 UTC, mirecki commented on app/controllers/api/v1/recipes_controller.rb
> +        params.require(:recipe).permit(%i[name content price video_link])
Add cooking_time since it will hit you anyway during conflicts

2021-08-02 08:45 UTC, mirecki commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +          post :create, params: { recipe: { name: '', content: '', price: '', video_link: '' } }
Same as above add cooking_time

2021-08-02 08:50 UTC, mirecki submitted a review, later dismissed
Seems ok

2021-08-02 09:56 UTC, Narzew approved these changes
Review OK, but small fixes needed to avoid conflicts, will be resolved during merge
new fields: price, cooking_time, level, video_link

2021-08-02 09:56 UTC, Narzew commented on app/controllers/api/v1/recipes_controller.rb
> +        params.require(:recipe).permit(%i[name content price video_link])
params.require(:recipe).permit(%i[name content price cooking_time level video_link])

2021-08-02 11:56 UTC, h4b00 submitted a review, later dismissed

2021-08-02 12:18 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +
remove empty line

2021-08-02 12:18 UTC, PatrykTyszka commented on db/seeds.rb
> +    tempor semper libero ultrices posuere. Maecenas id erat ac enim pharetra consequat.", price: 7, video_link: 'https://www.youtube.com/watch?v=KSIrBt6G5yQ',
It's hard to read maybe you should format it in this way?
``` 
Recipe.create(
  name: meal_name,
  content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. \
                  Aenean condimentum risus dui, volutpat consequat enim auctor quis. Sed eu elit egestas,
                  scelerisque quam quis, posuere libero. Fusce tincidunt sapien vel efficitur cursus. \
                  Nam a pretium purus, vel vestibulum mi. Aliquam erat volutpat. Morbi sed fermentum ante. Donec 
                  maximus lacinia libero, \
                  tempor semper libero ultrices posuere. Maecenas id erat ac enim pharetra consequat.",
  price: 7,
  video_link: 'https://www.youtube.com/watch?v=KSIrBt6G5yQ',
  cooking_time: 15
)

2021-08-02 12:18 UTC, PatrykTyszka commented on spec/serializers/recipe_serializer_spec.rb
> +      let(:recipe) { FactoryBot.build(:recipe) }
look at this line
```let(:recipe) { build(:recipe, price: nil) }```
once you wrote with FactoryBot and now it's without it. What's the reason? :)

2021-08-02 12:50 UTC, mirecki approved these changes

2021-08-03 07:31 UTC, PatrykTyszka approved these changes

2021-08-03 08:14 UTC, Narzew approved these changes

2021-08-03 08:15 UTC, merged