CB-4: Comments
knowde-academy/cookbook-be pull request #19
Opened 2021-08-04 12:05 UTC by Narzew

2021-08-04 23:20 UTC, PatrykTyszka commented on app/controllers/api/v1/comments_controller.rb
> +          render json: { errors: @comment.errors.to_s }, status: :unprocessable_entity
I don't get this? As I know @comment.errors.to_s returns sth like this: `"#<ActiveModel::Errors:0x00007fc621adde20>"` so maybe would be better to send @comment.errors.full_messages ?

2021-08-04 23:20 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +    if @instance_options[:context][:action] == 'show'
so if you want to use this Serializer without context I would go with this solution ->
```
@instance_options.fetch(:context, {})[:action] == 'show'
```
You won't get an exception if you forget to put context inside.

Besides I'm not sure if this solution is OK. Maybe, for now, we can leave it as is coz we have only one difference ( display comments only for SHOW action ) but if you'll have more than one check I would go with a separate Serializer to make this class more readable. You need to remember that DRY is important but READABILITY is better for sure ;)

2021-08-04 23:20 UTC, PatrykTyszka commented on config/routes.rb
> +        resources :comments
As I know resources method creates all routes including Edit and New. We need to create only these routes which we're using so please add `only` and show up exactly what you want to create.

2021-08-04 23:20 UTC, PatrykTyszka commented on spec/controllers/api/v1/comments_controller_spec.rb
> +end
missing specs ;)

2021-08-04 23:20 UTC, PatrykTyszka commented on spec/factories/comments.rb
> +    recipe_id { rand(1..4) }
wrong way! :D I agree that we can use rand for some number like `level` or sth but for recipe_id ( relation ) I don't agree for sure. Please create this relation in a proper way.

2021-08-09 12:46 UTC, h4b00 requested changes

2021-08-09 12:46 UTC, h4b00 commented on app/controllers/api/v1/recipes_controller.rb
> +      end
?

2021-08-09 12:46 UTC, h4b00 commented on app/models/recipe.rb
> +  has_many :comments
`dependent: :destroy`
https://guides.rubyonrails.org/association_basics.html#why-associations-questionmark

2021-08-09 12:46 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +    return nil if @instance_options.nil? or @instance_options[:context].nil? or @instance_options[:context][:action].nil?
1.  do not use `or` use `||`
2. `context[:action]` is not so much descriptive, use `context[:include_comments]`
3. What is the difference here?
```
      return nil if object.comments.empty?
      return nil unless object.comments
```

2021-08-09 12:46 UTC, h4b00 commented on spec/models/comment_spec.rb
> +
Unnecessary

2021-08-09 12:46 UTC, h4b00 commented on db/migrate/20210804092639_create_comments.rb
> +      t.string :body
I would protect it before being null

2021-08-09 12:46 UTC, h4b00 commented on spec/models/comment_spec.rb
> +  # comment = create :comment, recipe: recipe
?

2021-08-09 12:46 UTC, h4b00 commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      # byebug
?

2021-08-09 12:46 UTC, h4b00 commented on spec/factories/comments.rb
> +    recipe_id { recipe }
recipe
```suggestion
    body { Faker::Hacker.say_something_smart }
    recipe
```

2021-08-09 12:46 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +      object.comments
return unless @instance_options
```suggestion
    return [] unless @instance_options[:include_comments]
    
    object.comments
```

2021-08-09 12:46 UTC, h4b00 commented on app/controllers/api/v1/recipes_controller.rb
> +        render json: RecipeSerializer.new(@recipe, context: { action: 'show' }).to_h
```suggestion
        render json: RecipeSerializer.new(@recipe, include_options: true).to_h
```

2021-08-09 12:49 UTC, Narzew commented on app/controllers/api/v1/recipes_controller.rb
> +      end
Already deleted

2021-08-10 12:44 UTC, h4b00 requested changes

2021-08-10 12:44 UTC, h4b00 commented on app/controllers/api/v1/recipes_controller.rb
> +        render json: RecipeSerializer.new(@recipe, context: { include_comments: 'show' }).to_h
```suggestion
        render json: RecipeSerializer.new(@recipe, include_comments: true).to_h
```

2021-08-10 12:44 UTC, h4b00 commented on app/serializers/comment_serializer.rb
> +  delegate :body, to: :object
```suggestion
```

2021-08-10 12:44 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +
```suggestion
 return [] unless @instance_options[:include_comments]
```

2021-08-10 12:44 UTC, h4b00 commented on app/controllers/api/v1/recipes_controller.rb
> +                                                                               context: { include_comments: 'no' }) }
```suggestion
                                                                               include_comments: false) }
```

2021-08-10 12:50 UTC, h4b00 requested changes

2021-08-10 12:50 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +    end
```suggestion
    return [] unless @instance_options[:include_comments]

    object.comments
```

2021-08-10 12:50 UTC, h4b00 commented on db/migrate/20210804092639_create_comments.rb
> +      t.references :recipe
null false?

2021-08-10 12:50 UTC, h4b00 commented on app/models/comment.rb
> +  include ActiveModel::Validations
We don't need this

2021-08-10 12:50 UTC, h4b00 commented on spec/controllers/api/v1/comments_controller_spec.rb
> +  end
Not needed

2021-08-10 12:50 UTC, h4b00 commented on app/controllers/api/v1/comments_controller.rb
> +      end
Not needed

2021-08-10 12:50 UTC, h4b00 commented on app/controllers/api/v1/comments_controller.rb
> +      end
Same as above

2021-08-11 10:32 UTC, PatrykTyszka commented on app/controllers/api/v1/comments_controller.rb
> +        @comment = @recipe.comments.build(comment_params)
why instance variable instead of local variable?

2021-08-11 10:32 UTC, PatrykTyszka commented on Gemfile
> +  gem 'annotate', '~> 3.1.1', require: false
IMO this lib should be added in a separate PR.

2021-08-12 08:14 UTC, mirecki commented on Gemfile
> +  gem 'annotate', '~> 3.1.1', require: false
It was added by me and it was in separate PR or patch/ or approved by Adam to let be in one of my PR but I think first one. Dunno why it is displayed as his changes , probably due to late pull or smh

2021-08-12 11:56 UTC, Narzew commented on db/migrate/20210804092639_create_comments.rb
> +      t.references :recipe
Used to protect field from being null

2021-08-12 12:06 UTC, mirecki approved these changes

2021-08-12 12:49 UTC, PatrykTyszka commented on db/migrate/20210804092639_create_comments.rb
> +      t.references :recipe
@h4b00 If I good understood - @h4b00 wanted to know why you did not add null false here. am I right? :)

2021-08-12 12:49 UTC, PatrykTyszka commented on spec/controllers/api/v1/comments_controller_spec.rb
> +    end
just put these let's to the proper context.

2021-08-12 12:49 UTC, PatrykTyszka commented on spec/controllers/api/v1/comments_controller_spec.rb
> +
let(:call) { delete :destroy, params: { id: comment.id, recipe_id: recipe.id } }

and then...

expect { call }.to change ...

IMO this version is more readable.

2021-08-12 12:49 UTC, PatrykTyszka commented on spec/factories/comments.rb
> +    recipe_id { recipe }
does it work?

2021-08-12 23:25 UTC, h4b00 requested changes

2021-08-13 09:10 UTC, h4b00 requested changes

2021-08-13 09:10 UTC, h4b00 commented on config/routes.rb
> +        resources :comments, only: %i[index show create destroy]
where do you have index & show?

2021-08-13 11:16 UTC, h4b00 approved these changes

2021-08-13 11:18 UTC, PatrykTyszka approved these changes

2021-08-13 11:18 UTC, merged