CB-70 Add User model
knowde-academy/cookbook-be pull request #20
Opened 2021-08-06 12:16 UTC by grabomarcin

https://team-1626248039387.atlassian.net/browse/CB-70

2021-08-06 12:24 UTC, PatrykTyszka approved these changes

2021-08-06 12:24 UTC, PatrykTyszka commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
confirmable is a nice feature so we can add this as well ;) or you can add this later.

2021-08-06 12:24 UTC, PatrykTyszka commented on db/migrate/20210806120522_add_nickname_to_user.rb
> +    add_column :users, :nickname, :string, null: false
why did you add this as a separate migration?

2021-08-06 12:26 UTC, grabomarcin commented on db/migrate/20210806120522_add_nickname_to_user.rb
> +    add_column :users, :nickname, :string, null: false
I'll change that.

2021-08-06 12:29 UTC, mirecki requested changes

2021-08-06 12:29 UTC, mirecki commented on Gemfile
> +gem 'devise'
dodaj minimalna wersje w gemfile i dodaj to analogicznie do pozostałych i.e jak ma być na test/dev/prod to pod validate_url zeby nie bylo z tylka na koncu pliku ze jednak ten gem sie odnosi do wszystkich srodowisk

2021-08-06 12:45 UTC, grabomarcin commented on Gemfile
> +gem 'devise'
Fixed.

2021-08-06 13:58 UTC, mirecki approved these changes

2021-08-06 15:41 UTC, h4b00 requested changes

2021-08-06 15:41 UTC, h4b00 commented on app/models/user.rb
> +  validates :nickname, uniqueness: true, presence: true
Add validation for uniqueness email & presence

2021-08-06 15:41 UTC, h4b00 commented on spec/factories/users.rb
> +
Why empty?

2021-08-06 15:41 UTC, h4b00 commented on app/models/user.rb
> +  include ActiveModel::Validations
We don't need this I think.

2021-08-06 15:41 UTC, h4b00 commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
let's add this later

2021-08-09 08:52 UTC, h4b00 requested changes

2021-08-09 08:52 UTC, h4b00 commented on app/models/user.rb
> +  validates :email, uniqueness: true, presence: true
```suggestion
  validates :email, :nickname, uniqueness: true, presence: true
```

2021-08-09 08:52 UTC, h4b00 commented on spec/factories/users.rb
> +    nickname { Faker::Internet.username }
Do not use faker to generate unique fields.

Use https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#sequences

2021-08-09 08:52 UTC, h4b00 commented on spec/factories/users.rb
> +    password { Faker::Internet.password }
Same here ☝️

2021-08-09 08:52 UTC, h4b00 commented on spec/models/user_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Missing validations specs.

2021-08-09 08:52 UTC, h4b00 commented on spec/rails_helper.rb
> +  config.include Devise::Test::ControllerHelpers, type: :controller
👍

2021-08-09 09:47 UTC, Narzew approved these changes

2021-08-09 10:24 UTC, PatrykTyszka approved these changes

2021-08-09 12:01 UTC, h4b00 approved these changes
LGTM

2021-08-09 12:01 UTC, merged