Cb 5 add rating
knowde-academy/cookbook-be pull request #23
Opened 2021-08-11 07:04 UTC by grabomarcin

https://team-1626248039387.atlassian.net/browse/CB-5

2021-08-11 10:26 UTC, PatrykTyszka commented on app/controllers/api/v1/rates_controller.rb
> +          render json: rate
not sure if we should return the rate here. IMO information about recipe would be better. Please talk with the FE about that.

2021-08-11 10:26 UTC, PatrykTyszka commented on app/controllers/api/v1/rates_controller.rb
> +        rate = @recipe.rates.build(rate_params)
new is enough for sure in this case.

2021-08-11 10:26 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +  attributes :id, :name, :content, :video_link, :cooking_time, :level, :price, :average_rate
did you confirm this name with the FE?

2021-08-11 10:26 UTC, PatrykTyszka commented on config/routes.rb
> +        resources :rates, only: %i[ create ]
```suggestion
        resources :rates, only: %i[create]
```

2021-08-11 10:26 UTC, PatrykTyszka commented on config/routes.rb
> +
remove empty line

2021-08-11 10:26 UTC, PatrykTyszka commented on db/migrate/20210809160850_add_average_rate_to_recipe.rb
> +    add_column :recipes, :average_rate, :float, precision: 2, default: "0.0"
why not decimal ?

2021-08-11 10:26 UTC, PatrykTyszka commented on app/models/rate.rb
> +    recipe.save
```suggestion
    rates = receipe.rates
    
    return unless rates.present?
    
    recipe.update(average_rate: rates.sum(:value) / rates.size.to_f)
```

2021-08-11 10:26 UTC, PatrykTyszka commented on app/models/rate.rb
> +    recipe.save
think why we should return from the method when rates are an empty collection? :)

2021-08-11 10:26 UTC, PatrykTyszka commented on db/migrate/20210806081652_create_rates.rb
> +      t.references :recipe
why you did not add index for `receipe` IMO it would be usefull

2021-08-11 10:26 UTC, PatrykTyszka commented on spec/factories/users.rb
> +#
not sure why you added all comments in this PR :)
that could be done in a separate ticket.

2021-08-11 11:10 UTC, grabomarcin commented on spec/factories/users.rb
> +#
It generated automatically.

2021-08-11 11:11 UTC, PatrykTyszka commented on spec/factories/users.rb
> +#
yeah, I know but WHY? You did not add gem responsible for that so who did it? :)

2021-08-11 11:17 UTC, grabomarcin commented on db/migrate/20210809160850_add_average_rate_to_recipe.rb
> +    add_column :recipes, :average_rate, :float, precision: 2, default: "0.0"
I changed it to decimal, now I can set precision and scale.

2021-08-11 11:22 UTC, grabomarcin commented on spec/factories/users.rb
> +#
Michał added swagger to the project. When I created new branch from Develop it started generating these comments.

2021-08-11 11:25 UTC, PatrykTyszka commented on spec/factories/users.rb
> +#
who add this lib should generate comments as well :)

2021-08-11 11:28 UTC, grabomarcin commented on spec/factories/users.rb
> +#
Should I leave them?

2021-08-11 11:42 UTC, grabomarcin commented on app/serializers/recipe_serializer.rb
> +  attributes :id, :name, :content, :video_link, :cooking_time, :level, :price, :average_rate
Yes

2021-08-11 11:49 UTC, grabomarcin commented on app/models/rate.rb
> +    recipe.save
To avoid dividing by 0?

2021-08-11 11:51 UTC, PatrykTyszka commented on app/models/rate.rb
> +    recipe.save
yup

2021-08-13 11:32 UTC, grabomarcin commented on db/migrate/20210806081652_create_rates.rb
> +      t.references :recipe
It generated automatically.

2021-08-13 11:32 UTC, grabomarcin commented on config/routes.rb
> +
Fixed.

2021-08-13 11:33 UTC, grabomarcin commented on config/routes.rb
> +        resources :rates, only: %i[ create ]
Fixed.

2021-08-13 11:33 UTC, grabomarcin commented on app/controllers/api/v1/rates_controller.rb
> +        rate = @recipe.rates.build(rate_params)
Fixed.

2021-08-13 11:34 UTC, grabomarcin commented on app/controllers/api/v1/rates_controller.rb
> +          render json: rate
After conversation with FE we decided to return just status "200"

2021-08-13 12:42 UTC, PatrykTyszka approved these changes

2021-08-13 15:15 UTC, h4b00 requested changes

2021-08-13 15:15 UTC, h4b00 commented on app/models/rate.rb
> +    return if rates.blank?
how it can be nil, if this is after_create?

2021-08-13 15:15 UTC, h4b00 commented on app/models/rate.rb
> +    recipe.update(average_rate: rates.sum(:value) / rates.size.to_f)
in ruby we use `.count` for checking relation size.

2021-08-13 15:15 UTC, h4b00 commented on db/migrate/20210806081652_create_rates.rb
> +      t.references :user
we should add `null: false` for both columns

2021-08-13 15:15 UTC, h4b00 commented on spec/integration/api/v1/rates_spec.rb
> +        let(:rate) { create(:rate) }
why  `let(:rate) { create(:rate) }` ?

2021-08-13 15:15 UTC, h4b00 commented on spec/models/rate_spec.rb
> +  end
describe is invalid, you are not describing instance methods but callback.

`describe 'after_create #recalculate_rating'`
...
`it 'updates recipe avarage_rate'`

2021-08-13 15:15 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +  attributes :id, :name, :content, :video_link, :cooking_time, :level, :price, :comments, :average_rate
missing spec

2021-08-13 15:15 UTC, h4b00 commented on app/models/recipe.rb
> +  has_many :rates, dependent: :destroy
missing spec and please add to the rest
https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/association_matcher.rb#L328

2021-08-16 07:02 UTC, grabomarcin commented on app/models/rate.rb
> +    recipe.update(average_rate: rates.sum(:value) / rates.size.to_f)
Patryk sugested to use ` .size`

2021-08-16 08:19 UTC, grabomarcin commented on app/models/rate.rb
> +    return if rates.blank?
You're right, I removed it.

2021-08-16 08:19 UTC, grabomarcin commented on db/migrate/20210806081652_create_rates.rb
> +      t.references :user
Fixed.

2021-08-16 08:19 UTC, grabomarcin commented on spec/integration/api/v1/rates_spec.rb
> +        let(:rate) { create(:rate) }
I removed that.

2021-08-16 08:20 UTC, grabomarcin commented on spec/models/rate_spec.rb
> +  end
Fixed.

2021-08-16 08:21 UTC, grabomarcin commented on app/serializers/recipe_serializer.rb
> +  attributes :id, :name, :content, :video_link, :cooking_time, :level, :price, :comments, :average_rate
Fixed.

2021-08-16 08:59 UTC, grabomarcin commented on app/models/recipe.rb
> +  has_many :rates, dependent: :destroy
Fixed.

2021-08-16 09:01 UTC, grabomarcin commented on app/models/recipe.rb
> +  has_many :rates, dependent: :destroy
Fixed.

2021-08-16 09:11 UTC, h4b00 requested changes
Almost there, please add swagger spec for 422.

2021-08-16 09:11 UTC, h4b00 commented on db/migrate/20210816073230_modify_columns_in_rate.rb
> +    change_column :rates, :user_id, :bigint, null:false
Style
```suggestion
    change_column :rates, :recipe_id, :bigint, null: false
    change_column :rates, :user_id, :bigint, null: false
```

2021-08-16 09:11 UTC, h4b00 commented on spec/models/recipe_spec.rb
> +    it { should have_many(:comments) }
Add dependent here.

```
    #     # RSpec
      #     RSpec.describe Person, type: :model do
      #       it { should belong_to(:world).dependent(true) }
      #     end
```

2021-08-16 09:23 UTC, mirecki commented on spec/integration/api/v1/rates_spec.rb
> +require 'swagger_helper'
Verify later on heroku if you won't get any Swagger errors after PR since you wont see it on local version. I need to fix recipe's ones later or Nikodem can do it while he will be changing mine due to pagination implementation.

2021-08-16 09:25 UTC, mirecki approved these changes

2021-08-16 09:39 UTC, grabomarcin commented on spec/integration/api/v1/rates_spec.rb
> +require 'swagger_helper'
OK.

2021-08-16 09:51 UTC, h4b00 requested changes
1. Squash 2 migrations files (regarding rates) into 1.
2. I don't see an updated doc for swagger. Please run `rails rswag`

2021-08-16 10:52 UTC, grabomarcin commented on db/migrate/20210816073230_modify_columns_in_rate.rb
> +    change_column :rates, :user_id, :bigint, null:false
Fixed.

2021-08-16 10:52 UTC, grabomarcin commented on spec/models/recipe_spec.rb
> +    it { should have_many(:comments) }
Fixed.

2021-08-16 10:53 UTC, h4b00 approved these changes

2021-08-16 10:53 UTC, merged