CB-71: Add pagination
knowde-academy/cookbook-be pull request #26
Opened 2021-08-13 12:11 UTC by Narzew

2021-08-13 15:21 UTC, h4b00 requested changes
Missing:
- Response change
- Swagger specs
- New response specs.

2021-08-13 15:21 UTC, h4b00 commented on Gemfile
> +gem 'kaminari'
missing version

2021-08-13 15:21 UTC, h4b00 commented on app/controllers/api/v1/recipes_controller.rb
> +        @params_per_page = DEFAULT_PER_PAGE if @params_per_page.zero?
I would name it `per_page_param`

2021-08-13 15:21 UTC, h4b00 commented on app/controllers/api/v1/recipes_controller.rb
> +                                                                                                                     context: { include_comments: false }) }
you don't have to use this context, it's false by default right?

2021-08-16 11:31 UTC, h4b00 approved these changes

2021-08-16 11:31 UTC, h4b00 commented on spec/integration/api/v1/recipes_spec.rb
> +  let(:per_page) { rand(1..50) }
```suggestion
  let(:page) { 1 }
  let(:per_page) { 3 }
```

2021-08-16 11:38 UTC, mirecki approved these changes

2021-08-16 11:39 UTC, grabomarcin approved these changes

2021-08-16 11:40 UTC, merged