CB-11: Add sorting
knowde-academy/cookbook-be pull request #31
Opened 2021-08-18 07:55 UTC by Narzew

2021-08-18 07:57 UTC, mirecki approved these changes

2021-08-18 09:06 UTC, grabomarcin approved these changes
Seems OK.

2021-08-19 07:24 UTC, h4b00 requested changes

2021-08-19 07:24 UTC, h4b00 commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      get :index
move get to the before block `before { get :index, params: params }` and just control params by `let :params`

2021-08-19 07:24 UTC, h4b00 commented on app/controllers/api/v1/recipes_controller.rb
> +        recipes = Recipe.order(sort_column + ' ' + sort_direction).page(page).per(per_page)
this looks strange.
`sort_column => sort direction`

2021-08-19 07:36 UTC, Narzew commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      Recipe.delete_all
We have to test sorting on some records and if we don't know what we already have in a database, how could we know what we should expect at first and last value ? That's why I used approach of getting rid of all records from testing database, then inserting 5 records for sorting purposes and then checking the output of method used to sort to match corresponding records

2021-08-19 07:37 UTC, Narzew commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +          video_link: "https://samplevideolink.com/#{i + 1}"
I used it to generate different values, 'A' - 'E' in case of name, 10-50 in case of cooking time, 1-5 in case of level, 20-100 in case of price and 1.0-5.0 in case of average rate. The same with generating fake video links

2021-08-19 08:08 UTC, PatrykTyszka commented on app/controllers/api/v1/recipes_controller.rb
> +        recipes = Recipe.order(sort_column + ' ' + sort_direction).page(page).per(per_page)
+1

2021-08-19 08:08 UTC, PatrykTyszka commented on app/controllers/api/v1/recipes_controller.rb
> +        recipes = Recipe.order(sort_column + ' ' + sort_direction).page(page).per(per_page)
besides maybe would be better to move this logic to the model and create class method e.g .with_order()

2021-08-19 08:08 UTC, PatrykTyszka commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      Recipe.delete_all
but did you noticed that test does not work without `delete_all` ?

2021-08-19 08:08 UTC, PatrykTyszka commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +          video_link: "https://samplevideolink.com/#{i + 1}"
but Faker should take care of that

2021-08-19 08:08 UTC, PatrykTyszka commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      result = JSON.parse(response.body)['data']
use let instead of local variable

2021-08-19 08:08 UTC, PatrykTyszka commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      get :index, params: { sort: 'name', direction: 'asc' }
it should be in before and here you should only adjust params.

2021-08-19 08:51 UTC, Narzew commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      Recipe.delete_all
What's the proper way of doing that then? I want to check if sorting works properly, so I have decided to use some test records to check that behavior. How can I expect actual sorting behavior to be true on totally random data ? If I use .sort and .sort.reverse method on arrays, I would basically not test anything..

2021-08-19 11:42 UTC, Narzew commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      Recipe.delete_all
OK, I have fixed it by creating a data and using .first and .last method and comparing to that. Not sure if it's correct idea, but it doesn't require delete_all anymore

2021-08-19 11:43 UTC, Narzew commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +          video_link: "https://samplevideolink.com/#{i + 1}"
Code not valid anymore. I used simple create_list here with values from the factory.

2021-08-19 11:52 UTC, Narzew commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      get :index
I can't do let(:params) inside "it" blocks.. So I can't refactor the code this way

2021-08-19 11:52 UTC, Narzew commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      result = JSON.parse(response.body)['data']
Already extracted

2021-08-19 11:53 UTC, Narzew commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      result = JSON.parse(response.body)['data']
Done

2021-08-19 11:59 UTC, Narzew commented on app/controllers/api/v1/recipes_controller.rb
> +        recipes = Recipe.order(sort_column + ' ' + sort_direction).page(page).per(per_page)
I don't understand. What is exactly wrong there?
I basically build order('name asc') or order('name desc') here. It's very simple method.
Doesn't moving it to model create additional complexity ?

2021-08-20 12:32 UTC, sebastiansito requested changes

2021-08-20 12:32 UTC, sebastiansito commented on app/controllers/api/v1/recipes_controller.rb
> +                                                                                            per_page: params[:per_page])
You can fix indent
```suggestion
        recipes = Recipe.sorted(column: params[:sort], direction: params[:direction])
                        .paged(page: params[:page], per_page: params[:per_page])
```

2021-08-20 12:32 UTC, sebastiansito commented on app/controllers/api/v1/recipes_controller.rb
> +
You don't need that anymore

2021-08-20 12:32 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +  end
You should test all that in `User.sorted` spec. You removed logic from the controller but kept specs of that logic in controller spec.

2021-08-23 08:03 UTC, PatrykTyszka commented on app/models/recipe.rb
> +    order(column => direction)
1. Do not call local variables the same as arguments.
2. IMO you should show up explicitly through which columns we can sort.

```
column_name = SORTABLE_COLUMNS.include?(column) ? column : DEFAULT_SORT_DIRECTION
sort_direction = %i[asc desc].include?(direction) ? direction : DEFAULT_SORT_DIRECTION

order(column => direction)
```

2021-08-23 08:03 UTC, PatrykTyszka commented on spec/models/recipe_spec.rb
> +  describe '.sorted' do
missing specs for .paged method

2021-08-23 08:50 UTC, Narzew commented on spec/models/recipe_spec.rb
> +  describe '.sorted' do
Corrected. Specs added

2021-08-23 08:50 UTC, Narzew commented on app/models/recipe.rb
> +    order(column => direction)
Corrected

2021-08-23 09:03 UTC, PatrykTyszka approved these changes

2021-08-23 09:42 UTC, h4b00 approved these changes
LGTM but fix these 2 rubocop issues.

2021-08-23 09:42 UTC, h4b00 commented on app/models/recipe.rb
> +  SORTABLE_COLUMNS = %w[name cooking_time price level average_rate video_link]
why you didn't run rubocop?

2021-08-23 09:42 UTC, h4b00 commented on db/seeds.rb
> +    body: Faker::TvShows::Friends.quote + ' 1234567890'
same here? use rubocop

2021-08-23 10:19 UTC, merged