CB-8: Add sing in/sing out ( clean one)
knowde-academy/cookbook-be pull request #32
Opened 2021-08-18 12:09 UTC by mirecki

https://team-1626248039387.atlassian.net/jira/software/projects/CB/boards/1?selectedIssue=CB-8&text=BE

2021-08-18 12:44 UTC, Narzew approved these changes

2021-08-18 12:56 UTC, grabomarcin approved these changes

2021-08-19 09:53 UTC, h4b00 requested changes
Missing spec validation for `nickname`, missing specs for relations inside the user model.
Use shoulda-matcher for these.

2021-08-19 09:53 UTC, h4b00 commented on Gemfile
> +gem 'omniauth', '~> 2.0', '>= 2.0.4'
where do we use it?

2021-08-19 09:53 UTC, h4b00 commented on app/models/user.rb
> +  validate :validate_nickname
`(uniqueness: true)` is not enough?

2021-08-19 09:53 UTC, h4b00 commented on app/models/user.rb
> +  before_save -> { skip_confirmation! }
?

2021-08-19 09:53 UTC, h4b00 commented on app/models/user.rb
> +  validates :nickname, presence: true, uniqueness: true, format: { with: /^[a-zA-Z0-9_.]*$/, multiline: true }
multiline?

2021-08-19 09:53 UTC, h4b00 commented on app/models/user.rb
> +    @login || nickname || email
you have `presence: true` on the nickname

2021-08-19 09:53 UTC, h4b00 commented on db/migrate/20210806115824_devise_create_users.rb
> -# frozen_string_literal: true
you can't delete any migration. Create a new one that would drop this table.

2021-08-19 09:53 UTC, h4b00 commented on spec/factories/users.rb
> +    nickname { Faker::Internet.username(specifier: 3..30) }
username is unique, so you can't use faker for that.

2021-08-19 09:53 UTC, h4b00 commented on spec/factories/users.rb
> +    password { Faker::Internet.password(min_length: 6, max_length: 128, mix_case: true, special_characters: true) }
Where do you use it?

2021-08-19 11:24 UTC, mirecki commented on Gemfile
> +gem 'omniauth', '~> 2.0', '>= 2.0.4'
I wanted to use it but I am dum dum so it is just unnecessary , fixed now

2021-08-19 11:24 UTC, mirecki commented on app/models/user.rb
> +  validates :nickname, presence: true, uniqueness: true, format: { with: /^[a-zA-Z0-9_.]*$/, multiline: true }
fixed to be one line, no code validation from tutorial on my part

2021-08-19 11:24 UTC, mirecki commented on app/models/user.rb
> +    @login || nickname || email
As it suppose to if I understand it correctly, agreed with FE to nickname and email be required during sing up. It is just that you can log in via nickname or email as user wishes to. So there is no situation where nickname is not present

2021-08-19 11:24 UTC, mirecki commented on spec/factories/users.rb
> +    nickname { Faker::Internet.username(specifier: 3..30) }
added to be unique

2021-08-19 11:24 UTC, mirecki commented on spec/factories/users.rb
> +    password { Faker::Internet.password(min_length: 6, max_length: 128, mix_case: true, special_characters: true) }
fixed now since it is unnecessary code

2021-08-19 11:37 UTC, mirecki commented on app/models/user.rb
> +  before_save -> { skip_confirmation! }
I have went for lazy way of keeping confirmable stuff setup for future but not interfering with currently implemented and working. 
Fixed it properly to declare in environments localhost for mailer and implementation of set confirmation url to success to one , thing is that for whatever reason I cant make work "protect from forgery with null session" in app controller.
Was planning to do it and read why it is happening like that in separate CR when I wont be blocking other ppl with mine stuff.

2021-08-19 12:12 UTC, mirecki commented on spec/factories/users.rb
> +    nickname { Faker::Internet.username(specifier: 3..30) }
fixed with sequence

2021-08-19 12:25 UTC, mirecki commented on app/models/user.rb
> +  validate :validate_nickname
ok left only uniqueness then

2021-08-19 12:40 UTC, mirecki commented on db/migrate/20210806115824_devise_create_users.rb
> -# frozen_string_literal: true
fixed

2021-08-20 07:17 UTC, h4b00 requested changes

2021-08-20 07:17 UTC, h4b00 commented on app/models/user.rb
> +  validate :validate_nickname
So why it's still here?

2021-08-20 07:17 UTC, h4b00 commented on app/models/user.rb
> +    @login || nickname || email
exactly so login in your case is always nickname.

2021-08-20 07:17 UTC, h4b00 commented on spec/models/user_spec.rb
> +
?

2021-08-20 07:29 UTC, sebastiansito approved these changes
Pre-approved

2021-08-20 07:29 UTC, sebastiansito commented on app/models/user.rb
> +  extend Devise::Models
Let's move these to extensions

2021-08-20 07:29 UTC, sebastiansito commented on db/migrate/20210818112907_devise_token_auth_create_users.rb
> +class DeviseTokenAuthCreateUsers < ActiveRecord::Migration[6.1]
We can have only one migration.

2021-08-20 07:29 UTC, sebastiansito commented on db/migrate/20210818112907_devise_token_auth_create_users.rb
> +  def change
We should try to update existing table instead

2021-08-20 07:33 UTC, sebastiansito approved these changes

2021-08-20 07:33 UTC, sebastiansito commented on app/models/user.rb
> +    @login || nickname || email
Unless you write `user.login` at some point somewhere. We could use it at some point to override.

2021-08-20 07:36 UTC, sebastiansito commented on app/models/user.rb
> +  validate :validate_nickname
`uniqueness` won't check if someone has the same email as other user's nickname

2021-08-20 08:05 UTC, h4b00 approved these changes

2021-08-20 08:10 UTC, merged