Cb 13 limit recipes to logged users
knowde-academy/cookbook-be pull request #34
Opened 2021-08-20 11:50 UTC by mirecki

https://team-1626248039387.atlassian.net/jira/software/projects/CB/boards/1?selectedIssue=CB-13&text=BE

2021-08-23 12:57 UTC, Narzew approved these changes

2021-08-24 07:16 UTC, grabomarcin approved these changes

2021-08-24 07:16 UTC, grabomarcin commented on spec/controllers/api/v1/rates_controller_spec.rb
> +>>>>>>> b83e8f00489ed086eef6612b4584c83476da3f24
You left some comments.

2021-08-24 07:23 UTC, mirecki commented on spec/controllers/api/v1/rates_controller_spec.rb
> +>>>>>>> b83e8f00489ed086eef6612b4584c83476da3f24
fixed

2021-08-31 09:28 UTC, h4b00 requested changes

2021-08-31 09:28 UTC, h4b00 commented on app/models/user.rb
> +    type == 'SystemUser'
don't use magic strings, use consts or enums.

2021-08-31 09:28 UTC, h4b00 commented on lib/tasks/set_system_user_for_all_existing_recipes.rake
> +  end
`.update_all` ?

2021-08-31 09:28 UTC, h4b00 commented on app/models/system_user.rb
> +class SystemUser < User
missing model spec?

2021-08-31 09:28 UTC, h4b00 commented on Gemfile
> -gem 'devise', '~> 4.8.0'
missing gemfile.lock change

2021-08-31 09:40 UTC, PatrykTyszka requested changes

2021-08-31 09:40 UTC, PatrykTyszka commented on lib/tasks/create_system_user.rake
> +  return puts new_sys_user.errors.messages unless new_sys_user.valid?
i.e new_sys_user is invalid ... and ? xD 
who will take care of that? Are you gonna check the logs? Besides, you won't see puts inside logs so you should use Rails.logger here.

2021-08-31 09:40 UTC, PatrykTyszka commented on lib/tasks/set_system_user_for_all_existing_recipes.rake
> +  end
it should be done in one QUERY.

2021-08-31 09:40 UTC, PatrykTyszka commented on app/services/system_user_service.rb
> +end
Do you really need this service?

2021-08-31 09:45 UTC, mirecki commented on db/migrate/20210824091240_add_system_user_in_rake_task.rb
> +end
Adam's order

2021-08-31 09:50 UTC, mirecki commented on Gemfile
> -gem 'devise', '~> 4.8.0'
It actually not my fault of not running after that bundle update or bundle clean --force and then install. Gemlock file addition of devise is made by devise_token_auth lib. Only after commenting deivse_token_auth gem in Gemfile there is no more addition of that line in gemlock file.

2021-08-31 09:59 UTC, mirecki commented on app/controllers/api/v1/recipes_controller.rb
> +      DEFAULT_PER_PAGE = 24
I have no idea, not my garbage. Nikodem was doing pagination

2021-08-31 10:04 UTC, Narzew commented on app/controllers/api/v1/recipes_controller.rb
> +      DEFAULT_PER_PAGE = 24
He has old version, this don't exist in my code anymore, in develop neither

2021-08-31 10:16 UTC, mirecki commented on app/models/system_user.rb
> +    return true if SystemUser.first.blank?
corrected

2021-08-31 10:16 UTC, mirecki commented on app/models/system_user.rb
> +    false
corrected

2021-08-31 10:26 UTC, mirecki commented on app/services/system_user_service.rb
> +end
Yep it is unnecessary code from before. Deleted since I am doing now everything in tasks

2021-08-31 12:56 UTC, Narzew commented on app/models/system_user.rb
> +    errors.add(:base, 'SystemUser already exists') unless SystemUser.exists?
Masz tu błąd w logice. Powinieneś sprawdzić czy użytkownik istnieje a nie czy użytkownika nie ma.
Poprawna forma:
`errors.add(:base, 'SystemUser already exists') if SystemUser.exists?`

2021-08-31 12:56 UTC, Narzew commented on app/models/system_user.rb
> +    errors.add(:base, 'SystemUser already exists') unless SystemUser.exists?
errors.add doesn't work properly. Needs to  be fixed

2021-08-31 12:56 UTC, Narzew commented on app/models/system_user.rb
> +class SystemUser < User
Doesn't SystemUser inherit from User? User was already tested, should we make specs for SystemUser too without breaking DRY principle ?

2021-08-31 13:14 UTC, mirecki commented on lib/tasks/set_system_user_for_all_existing_recipes.rake
> +  end
done

2021-08-31 13:14 UTC, mirecki commented on lib/tasks/set_system_user_for_all_existing_recipes.rake
> +  end
done

2021-08-31 13:26 UTC, mirecki commented on app/models/user.rb
> +    type == 'SystemUser'
Please verify my solution, since I am not sure if this is what you are asking

2021-09-01 06:51 UTC, mirecki commented on app/models/system_user.rb
> +class SystemUser < User
Added some, for more I need more specific examples also wondering about this inheritance and test regarding it

2021-09-01 06:58 UTC, mirecki commented on db/migrate/20210824091240_add_system_user_in_rake_task.rb
> +end
ok changed to insert code into migration instead of rake tasks. I misunderstood what Adam wanted.

2021-09-01 07:06 UTC, mirecki commented on lib/tasks/create_system_user.rake
> +  return puts new_sys_user.errors.messages unless new_sys_user.valid?
deleted rake tasks

2021-09-01 07:22 UTC, mirecki commented on app/models/system_user.rb
> +    errors.add(:base, 'SystemUser already exists') unless SystemUser.exists?
works correctly , we just dont undestrand how actually. We could make our own validator system to display errors in console etc if we would like to but I would put it in another task to not block ppl with current one.

2021-09-01 08:45 UTC, h4b00 requested changes

2021-09-01 08:45 UTC, h4b00 commented on app/models/recipe.rb
> +  validates :user_id, presence: true
Do not validates `user_id` column, validate relation.
```suggestion
  validates :user, presence: true
```

2021-09-01 08:45 UTC, h4b00 commented on db/migrate/20210824091240_add_system_user_and_assign_all_recipes.rb
> +class AddSystemUserInRakeTask < ActiveRecord::Migration[6.1]
it's not rake task

2021-09-01 08:45 UTC, h4b00 commented on db/migrate/20210824091240_add_system_user_and_assign_all_recipes.rb
> +    new_sys_user.save
use bangs! everywhere to avoid soft fail.

2021-09-01 08:45 UTC, h4b00 commented on spec/models/system_user_spec.rb
> +    it { expect(described_class.count).to be <= 1 }
that's strange
use `.eq`

2021-09-01 09:03 UTC, mirecki commented on spec/models/system_user_spec.rb
> +    it { expect(described_class.count).to be <= 1 }
done

2021-09-01 09:03 UTC, mirecki commented on db/migrate/20210824091240_add_system_user_and_assign_all_recipes.rb
> +class AddSystemUserInRakeTask < ActiveRecord::Migration[6.1]
yep, I missed this with changing the name

2021-09-01 09:06 UTC, mirecki commented on db/migrate/20210824091240_add_system_user_and_assign_all_recipes.rb
> +    new_sys_user.save
done

2021-09-01 09:22 UTC, mirecki commented on app/models/recipe.rb
> +  validates :user_id, presence: true
changed

2021-09-01 10:06 UTC, PatrykTyszka approved these changes

2021-09-01 10:06 UTC, PatrykTyszka commented on app/models/system_user.rb
> +class SystemUser < User
@Narzew If we have some differences between User and SystemUser - we should test it for sure.

2021-09-01 10:06 UTC, PatrykTyszka commented on db/migrate/20210824091240_add_system_user_and_assign_all_recipes.rb
> +    Recipe.update_all! user_id: SystemUser.first.id
You can add it to the `AddUserReferenceToRecipes`. These actions seem to be linked.

2021-09-01 10:28 UTC, h4b00 approved these changes

2021-09-01 11:09 UTC, mirecki commented on db/migrate/20210824091240_add_system_user_and_assign_all_recipes.rb
> +    Recipe.update_all! user_id: SystemUser.first.id
ok done.

2021-09-01 11:09 UTC, merged