Cb-14 (DRAFT Limit comments to logged users)
knowde-academy/cookbook-be pull request #40
Opened 2021-09-01 12:28 UTC by Narzew

Only a draft.
9 more RSpec errors yet to solve.

2021-09-01 12:40 UTC, mirecki approved these changes

2021-09-01 13:02 UTC, mirecki commented on app/controllers/api/v1/comments_controller.rb
>        before_action :set_comment, except: %i[create]
this one

2021-09-02 08:05 UTC, mirecki commented on db/migrate/20210820113616_add_user_reference_to_recipes_and_create_system_user.rb
> +class AddUserReferenceToRecipesAndCreateSystemUser < ActiveRecord::Migration[6.1]
On last commit in my PR I havent noticed that after name change of migration it became untracked by git and I merged without last one. Made a patch afterwards but we decided to merge it with Nikodem's PR. 
There was also small adjustment to cores since they were not working as FE wanted

2021-09-02 08:40 UTC, grabomarcin approved these changes

2021-09-02 08:40 UTC, grabomarcin commented on spec/models/system_user_spec.rb
> +  let!(:SystemUser) { create(:SystemUser) }
Schould it be duplicated?

2021-09-02 09:00 UTC, Narzew commented on spec/models/system_user_spec.rb
> +  let!(:SystemUser) { create(:SystemUser) }
Rubocop artifact. Fixed

2021-09-02 09:01 UTC, mirecki commented on spec/models/system_user_spec.rb
> +  let!(:SystemUser) { create(:SystemUser) }
yes because we test if only 1 user is allowed to be created, it could have been written more nicely tho in one line but works xd

2021-09-02 09:08 UTC, Narzew commented on spec/models/system_user_spec.rb
> +  let!(:SystemUser) { create(:SystemUser) }
Yes because we create two SystemUsers and check if only one got created

2021-09-02 09:25 UTC, PatrykTyszka commented on app/controllers/api/v1/comments_controller.rb
> +        comment.recipe_id = @recipe.id
@recipe.comments.new(comment_params.merge(user: current_api_v1_user)

2021-09-02 09:27 UTC, PatrykTyszka commented on app/serializers/comment_serializer.rb
> +  delegate :id, to: :object
useless

2021-09-02 09:28 UTC, PatrykTyszka commented on config/initializers/cors.rb
> +             expose: %w[access-token token-type client expiry uid]
use env

2021-09-02 12:07 UTC, PatrykTyszka commented on app/controllers/api/v1/comments_controller.rb
> +        params.require(:comment).permit(%i[id author body recipe_id])
id ? :D wat?

2021-09-02 12:07 UTC, PatrykTyszka commented on app/models/user.rb
> +    System_user.type == SYSTEM_USER_TYPE
? it will raise exception

2021-09-02 12:10 UTC, Narzew commented on app/controllers/api/v1/comments_controller.rb
> +        params.require(:comment).permit(%i[id author body recipe_id])
id of the comment for frontend to operate at, did I understand something wrong?

2021-09-02 12:10 UTC, mirecki commented on app/models/user.rb
> +    System_user.type == SYSTEM_USER_TYPE
well it would but I reverted to SystemUser.type, will check why this is like that in repo if I have correct thing in local

2021-09-02 12:35 UTC, mirecki commented on app/controllers/api/v1/comments_controller.rb
> +        params.require(:comment).permit(%i[id author body recipe_id])
fixed, id in params was useless

2021-09-02 13:10 UTC, PatrykTyszka requested changes

2021-09-02 13:10 UTC, PatrykTyszka commented on db/migrate/20210820113616_add_user_reference_to_recipes.rb
> -end
NOP

2021-09-03 07:10 UTC, mirecki commented on db/migrate/20210820113616_add_user_reference_to_recipes.rb
> -end
Fixed

2021-09-03 07:12 UTC, PatrykTyszka approved these changes

2021-09-03 07:12 UTC, PatrykTyszka commented on db/migrate/20210820113616_add_user_reference_to_recipes.rb
>  end
differen indentation

2021-09-03 07:12 UTC, PatrykTyszka commented on db/migrate/20210820113616_add_user_reference_to_recipes.rb
> +
empty line at the end of file

2021-09-03 07:12 UTC, PatrykTyszka commented on db/migrate/20210820113618_add_user_reference_to_recipes_and_create_system_user.rb
> +      Recipe.update_all user_id: SystemUser.first.id
Recipe.update_all user_id: SystemUser.instance.id
and you can remove line 5

2021-09-03 07:12 UTC, PatrykTyszka commented on db/migrate/20210902073444_add_user_reference_to_comments.rb
> +    Comment.update_all user_id: SystemUser.first.id
Same here

2021-09-03 07:35 UTC, merged