CB-74: Add possibility to add photos of recipe
knowde-academy/cookbook-be pull request #41
Opened 2021-09-02 10:07 UTC by grabomarcin

https://team-1626248039387.atlassian.net/browse/CB-74

2021-09-07 10:02 UTC, plokijro commented on app/models/image.rb
> +  validates :photo, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']
Use constant

2021-09-07 10:03 UTC, mirecki approved these changes

2021-09-07 10:07 UTC, Narzew approved these changes

2021-09-08 13:57 UTC, h4b00 requested changes
Why swagger.json is much smaller than before?

2021-09-08 13:57 UTC, h4b00 commented on app/controllers/api/v1/images_controller.rb
> +        service = ImagesService.new(image_params, @recipe)
ImagesService sounds a bit too general, let's maybe name it `ImagesServiceCreator`
I am a big fan of using kargs if I have more than 1 argument.

2021-09-08 13:57 UTC, h4b00 commented on app/controllers/api/v1/images_controller.rb
> +          render status: :ok
```suggestion
          render status: :created
```

cuz ok returns `200` but you should return here `201`

2021-09-08 13:57 UTC, h4b00 commented on app/controllers/api/v1/images_controller.rb
> +        end
Do you have a CRUD action for destroying multiple resources?

2021-09-08 13:57 UTC, h4b00 commented on app/services/images_service.rb
> +      end
That sounds strange why do we want to upload multiple files like this at once?
I mean every time when you guys upload multiple files, In the background you are doing this one by one.
So you don't have a problem with upload file size limit

2021-09-09 07:22 UTC, grabomarcin commented on app/controllers/api/v1/images_controller.rb
> +        end
I  did it in Image service, it gets an array of id's and destroys them.

2021-09-09 07:22 UTC, grabomarcin commented on app/services/images_service.rb
> +      end
Would it be a better solution if FE hit several times in end-point sending photos one by one?

2021-09-09 07:31 UTC, grabomarcin commented on app/controllers/api/v1/images_controller.rb
> +        service = ImagesService.new(image_params, @recipe)
Good point. I changed that

2021-09-09 07:31 UTC, grabomarcin commented on app/controllers/api/v1/images_controller.rb
> +          render status: :ok
Fixed.

2021-11-05 09:37 UTC, closed without merging